=== lumialfe/SEW/practica2/Ejercicio-2/Tarea-2/rutas.dtd
<?xml encoding="utf-8"?>

<!ELEMENT rutas (ruta)+>
<!ATTLIST rutas
  xmlns CDATA #FIXED ''>

<!ELEMENT ruta (dificultad,fecha?,hora?,duracion,agencia,descripcion,
                restricciones,inicio,direccion_inicio,coordenadas,
                referencias,valoracion,hitos)>
<!ATTLIST ruta
  xmlns CDATA #FIXED ''
  nombre CDATA #REQUIRED
  tipo CDATA #REQUIRED>

<!ELEMENT dificultad (#PCDATA)>
<!ATTLIST dificultad
  xmlns CDATA #FIXED ''>

<!ELEMENT fecha (#PCDATA)>
<!ATTLIST fecha
  xmlns CDATA #FIXED ''>

<!ELEMENT hora (#PCDATA)>
<!ATTLIST hora
  xmlns CDATA #FIXED ''>

<!ELEMENT duracion (#PCDATA)>
<!ATTLIST duracion
  xmlns CDATA #FIXED ''>

<!ELEMENT agencia (#PCDATA)>
<!ATTLIST agencia
  xmlns CDATA #FIXED ''>

<!ELEMENT restricciones (restriccion)*>
<!ATTLIST restricciones
  xmlns CDATA #FIXED ''>

<!ELEMENT inicio (#PCDATA)>
<!ATTLIST inicio
  xmlns CDATA #FIXED ''>

<!ELEMENT direccion_inicio (#PCDATA)>
<!ATTLIST direccion_inicio
  xmlns CDATA #FIXED ''>

<!ELEMENT referencias (referencia)+>
<!ATTLIST referencias
  xmlns CDATA #FIXED ''>

<!ELEMENT valoracion (#PCDATA)>
<!ATTLIST valoracion
  xmlns CDATA #FIXED ''>

<!ELEMENT hitos (hito)+>
<!ATTLIST hitos
  xmlns CDATA #FIXED ''>

<!ELEMENT restriccion (#PCDATA)>
<!ATTLIST restriccion
  xmlns CDATA #FIXED ''
  tipo NMTOKEN #REQUIRED>

<!ELEMENT referencia (#PCDATA)>
<!ATTLIST referencia
  xmlns CDATA #FIXED ''>

<!ELEMENT hito (descripcion,coordenadas,distancia_desde_anterior, tiempo_desde_anterior,galeria)>
<!ATTLIST hito
  xmlns CDATA #FIXED ''
  nombre CDATA #REQUIRED>

<!ELEMENT distancia_desde_anterior (#PCDATA)>
<!ATTLIST distancia_desde_anterior
  xmlns CDATA #FIXED ''
  unidades CDATA #REQUIRED>

<!ELEMENT tiempo_desde_anterior (#PCDATA)>
<!ATTLIST tiempo_desde_anterior
  xmlns CDATA #FIXED ''>

<!ELEMENT galeria (fotos+,videos*)>
<!ATTLIST galeria
  xmlns CDATA #FIXED ''>

<!ELEMENT fotos (foto)+>
<!ATTLIST fotos
  xmlns CDATA #FIXED ''>

<!ELEMENT videos (video)+>
<!ATTLIST videos
  xmlns CDATA #FIXED ''>

<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto
  xmlns CDATA #FIXED ''>

<!ELEMENT video (#PCDATA)>
<!ATTLIST video
  xmlns CDATA #FIXED ''>

<!ELEMENT descripcion (#PCDATA)>
<!ATTLIST descripcion
  xmlns CDATA #FIXED ''>

<!ELEMENT coordenadas (latitud,longitud,altitud)>
<!ATTLIST coordenadas
  xmlns CDATA #FIXED ''>

<!ELEMENT latitud (#PCDATA)>
<!ATTLIST latitud
  xmlns CDATA #FIXED ''>

<!ELEMENT longitud (#PCDATA)>
<!ATTLIST longitud
  xmlns CDATA #FIXED ''>

<!ELEMENT altitud (#PCDATA)>
<!ATTLIST altitud
  xmlns CDATA #FIXED ''>

=== lumialfe/SEW/practica2/Ejercicio-2/Tarea-1/rutas.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
    <rutas>
        <ruta nombre = "Mirando al Mar" tipo ="Ruta a Caballo">
            <dificultad>Facil</dificultad>
            <fecha>2021-06-06</fecha>
            <duracion>PT1H</duracion>
            <agencia>Yumping.com</agencia>
            <descripcion>Es una ruta de contacto con la naturaleza, disfrutando de los incomparables paisajes asturianos de mar y montaña.</descripcion>
            <restricciones>
                <restriccion tipo ="edad">Niños a partir de 6 años</restriccion>
            </restricciones>
            <inicio>Lamuño</inicio>
            <direccion_inicio>CU-6, 2</direccion_inicio>
            <coordenadas>
                <longitud>43.5644678</longitud>
                <latitud>-6.2118458</latitud>
                <altitud>116</altitud>
            </coordenadas>
            <referencias>
                <referencia>https://www.yumping.com/ofertas/rutas-a-caballo/asturias/ruta-a-caballo-en-lamuno-mirando-al-mar-1-hora--o22299</referencia>
                <referencia>https://www.yumping.com/rutas-a-caballo/asturias</referencia>
                <referencia>https://www.yumping.com/rutas-a-caballo/asturias/lamuno-cudillero</referencia>
            </referencias>
            <valoracion>8</valoracion>
            <hitos>
                <hito nombre="Lamuño">
                    <descripcion>Inicio de Ruta</descripcion>
                    <coordenadas>
                        <longitud>43.56446</longitud>
                        <latitud>-6.21184</latitud>
                        <altitud>116</altitud>
                    </coordenadas>
                    <distancia_desde_anterior unidades="m">0</distancia_desde_anterior>
                    <tiempo_desde_anterior>0</tiempo_desde_anterior>
                    <galeria>
                        <fotos>
                            <foto>
                                https://media2.clubrural.com/img990x400/pueblos/asturias/lamuno/20160218201624-asturias-lamuno.jpg
                            </foto>
                        </fotos>
                    </galeria>
                </hito>

                <hito nombre="Area Recreativa de Monte Balsera">
                    <descripcion>Punto de interés</descripcion>
                    <coordenadas>
                        <longitud>43.57</longitud>
                        <latitud>-6.21</latitud>
                        <altitud>118</altitud>
                    </coordenadas>
                  <distancia_desde_anterior unidades="m">800</distancia_desde_anterior>
                    <tiempo_desde_anterior>0.2</tiempo_desde_anterior>
                    <galeria>
                        <fotos>
                            <foto>
                                https://cmsphoto.ww-cdn.com/resizeapi/ffbd226e233c64ab80ab37ec776650559a1f8be6/3200/-1/
                            </foto>
                        </fotos>
                    </galeria>
                </hito>

                <hito nombre="Concha de Artedo">
                    <descripcion>Fin de Ruta</descripcion>
                    <coordenadas>
                        <longitud>43.3403</longitud>
                        <latitud>-6.1131</latitud>
                        <altitud>0</altitud>
                    </coordenadas>
                  <distancia_desde_anterior unidades="m">2200</distancia_desde_anterior>
                    <tiempo_desde_anterior>0.8</tiempo_desde_anterior>
                    <galeria>
                        <fotos>
                            <foto>
                                https://upload.wikimedia.org/wikipedia/commons/1/15/Concha_de_Artedo.JPG                       
                            </foto>
                            <foto>
                                https://saposyprincesas.elmundo.es/wp-content/uploads/2019/07/playa-de-concha-de-artedo.jpg

                            </foto>
                            <foto>
                                https://www.turismoasturias.es/documents/11022/13503/PlayaConchaArtedo3.jpg?t=1388684032544
                            </foto>
                        </fotos>
                        <videos>
                            <video>https://www.youtube.com/watch?v=p4KRIVzKtM0</video>
                        </videos>
                    </galeria>
                </hito>
            </hitos>
        </ruta>

        <ruta nombre = "Ruta a Caballo en Arriondas" tipo ="Ruta a Caballo">
            <dificultad>Facil</dificultad>
            <duracion>PT2H</duracion>
            <agencia>aventurasenasturias.com</agencia>
            <descripcion>Estas rutas recorren bosques y montañas con impresionantes vistas de la Cordillera del Sueve y de los Picos de Europa.</descripcion>
            <restricciones>
                <restriccion tipo ="edad">Niños a partir de 9 años</restriccion>
                <restriccion tipo ="altura">Niños a partir de 1.30m</restriccion>
            </restricciones>           
            <inicio>Arriondas</inicio>
            <direccion_inicio>Cuadras de Arriondas</direccion_inicio>
            <coordenadas>
                <longitud>43.2325</longitud>
                <latitud>-5.1110</latitud>
                <altitud>36</altitud>
            </coordenadas>
            <referencias>
                <referencia>https://www.aventurasenasturias.com/aventuras_en_asturias_actividades.php?aventurasID=171</referencia>
                <referencia>https://www.yumping.com/rutas-a-caballo/asturias/arriondas</referencia>
                <referencia>https://www.loscauces.com/rutas-a-caballo-en-asturias/</referencia>
            </referencias>
            <valoracion>9</valoracion>
            <hitos>
                <hito nombre="Arriondas">
                    <descripcion>Inicio de Ruta</descripcion>
                    <coordenadas>
                        <longitud>43.2325</longitud>
                        <latitud>-5.1110</latitud>
                        <altitud>36</altitud>
                    </coordenadas>
                  <distancia_desde_anterior unidades="m">0</distancia_desde_anterior>
                    <tiempo_desde_anterior>0</tiempo_desde_anterior>
                    <galeria>
                        <fotos>
                            <foto>
                                https://jairecanoas.com/blog/wp-content/uploads/2019/11/arriondas-825x510.jpg                            
                            </foto>
                        </fotos>
                    </galeria>
                </hito>

                <hito nombre="Coviella">
                    <descripcion>Punto de interés</descripcion>
                    <coordenadas>
                        <longitud>43.2318</longitud>
                        <latitud>-5.1023</latitud>
                        <altitud>85</altitud>
                    </coordenadas>
                  <distancia_desde_anterior unidades="m">600</distancia_desde_anterior>
                    <tiempo_desde_anterior>0.2</tiempo_desde_anterior>
                    <galeria>
                        <fotos>
                            <foto>
                                https://fotos01.lne.es/2011/08/06/318x200/2011-08-13_IMG_2011-08-06_03.06.07__6919826.jpg                        
                            </foto>
                        </fotos>
                    </galeria>
                </hito>

                <hito nombre="Picos de Europa">
                    <descripcion>Fin de Ruta</descripcion>
                    <coordenadas>
                        <longitud>43.1106</longitud>
                        <latitud>-4.4917</latitud>
                        <altitud>2500</altitud>
                    </coordenadas>
                  <distancia_desde_anterior unidades="m">2800</distancia_desde_anterior>
                    <tiempo_desde_anterior>0.8</tiempo_desde_anterior>
                    <galeria>
                        <fotos>
                            <foto>
                                https://www.plea.es/sites/default/files/styles/plea_cabecera_blog/public/pico-urrellu-famoso-por-escaladas-realizadas-en-el.jpg?itok=KiIO4fK7                        </foto>
                            <foto>
                                https://www.turismoasturias.es/documents/11022/4994980/PORTADA-bulnes-Mampiris.jpg/25820526-124c-4430-a2a0-9716a472fa62?t=1588852703233
                            </foto>
                            <foto>
                                https://i.blogs.es/b922c5/el-parque-nacional-picos-de-europa-cumple-100-anos/1366_2000.jpg                        
                            </foto>
                        </fotos>
                        <videos>
                            <video>https://www.youtube.com/watch?v=FHgKpk1SyAM</video>
                        </videos>
                    </galeria>
                </hito>
            </hitos>
        </ruta>

        <ruta nombre = "Caballos en Cudillero" tipo ="Ruta a Caballo">
            <dificultad>Media</dificultad>
            <hora>17:00:00</hora>
            <duracion>PT2H</duracion>
            <agencia>aventurasenasturias.com</agencia>
            <descripcion>Estas rutas se realizan en el entorno de Cudillero, en la zona central de Asturias cerca de Avilés, Gijón y de Oviedo.</descripcion>
            <restricciones>
                <restriccion tipo ="edad">Niños a partir de 6 años</restriccion>
                <restriccion tipo ="numero">Máximo de 12 personas</restriccion>
            </restricciones>
            <inicio>Cudillero</inicio>
            <direccion_inicio>Hípica de Cudillero</direccion_inicio>
            <coordenadas>
                <longitud>43.3357</longitud>
                <latitud>-6.1235</latitud>
                <altitud>126</altitud>
            </coordenadas>
            <referencias>
